### ISSUE TITLE
The training time and GPU memory consumption.

### ISSUE THREAD

**Issue by LZ-CH** [LaVi-Lab/Video-3D-LLM#1] opened 2024-12-04 09:42 UTC
Hi, thanks for posting this great work, I would like to know how much time and GPU memory consumption it takes while training.

**Comment by zd11024** [comment] 2024-12-04 11:07
Thanks for your attention! 
Under the 32-frame uniform sampling setting, it takes around 32 hours with 8 A100(80G) GPUS, each with ~60G GPU memory usage.

**Comment by LZ-CH** [comment] 2024-12-05 07:24
Thanks for your reply. In order to reduce the memory usage, I want to use lora for fine-tuning. Have you tried to use lora to fine-tune your model? I observed that I can set the lora_enable parameter to enable lora configuration, but I don't know if your project is compatible with this parameter.

**Comment by zd11024** [comment] 2024-12-05 08:05
Yes, we have tried LoRA, which has a similar performance compared to full fine-tuning.  You could try the option `lora-enable` directly.

**Comment by LZ-CH** [comment] 2024-12-09 11:06
When I run train_multi.sh and set lora-enable, I encountered the following problem. Have you ever encountered such a problem? 
```shell
  File "/user/anaconda3/envs/v3d/lib/python3.10/site-packages/peft/tuners/lora.py", line 352, in _find_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target)
  File "/user/anaconda3/envs/v3d/lib/python3.10/site-packages/peft/tuners/lora.py", line 305, in _create_new_module
    raise ValueError(
ValueError: Target module Qwen2DecoderLayer(
  (self_attn): Qwen2FlashAttention2(
    (q_proj): Linear(in_features=3584, out_features=3584, bias=True)
    (k_proj): Linear(in_features=3584, out_features=512, bias=True)
    (v_proj): Linear(in_features=3584, out_features=512, bias=True)
    (o_proj): Linear(in_features=3584, out_features=3584, bias=False)
    (rotary_emb): Qwen2RotaryEmbedding()
  )
  (mlp): Qwen2MLP(
    (gate_proj): Linear(in_features=3584, out_features=18944, bias=False)
    (up_proj): Linear(in_features=3584, out_features=18944, bias=False)
    (down_proj): Linear(in_features=18944, out_features=3584, bias=False)
    (act_fn): SiLU()
  )
  (input_layernorm): Qwen2RMSNorm()
  (post_attention_layernorm): Qwen2RMSNorm()
) is not supported. Currently, only `torch.nn.Linear` and `Conv1D` are supported. 
```

**Comment by zd11024** [comment] 2024-12-09 13:41
This is caused by the addtional grounding head. I have fixed this bug in the latest commit.

**Comment by LZ-CH** [comment] 2024-12-09 16:24
Cool! Now Lora can be used normally!!!! 

However, when I try to set ```--per_device_train_batch_size``` to greater than or equal to 2 (It is normal when set to 1), when merging video dict data in multiple threads of dataloader, it fails to merge properly because the number of objects in each scene is inconsistent. 

This is caused by the following [code](https://github.com/LaVi-Lab/Video-3D-LLM/blob/b0d65150183f13eab0b4a42601ec93381057d227/llava/video_utils.py#L366):
```python

def merge_video_dict(video_dict_list):
    new_video_dict = {}
    new_video_dict['box_input'] = []
    for k in video_dict_list[0]:
        if k in ["world_coords", 'images', 'objects']:
            # When batch_size is greater than 1, the number of objects in different scenes may be different
            new_video_dict[k] = torch.stack([video_dict[k] for video_dict in video_dict_list])
        elif k in ['box_input']:
            for video_dict in video_dict_list:
                if video_dict[k] is not None:
                    new_video_dict['box_input'].append(video_dict[k])

```

I want to know if it is possible to support multi-batch training to reduce the training time under Lora?

**Comment by zd11024** [comment] 2024-12-10 02:00
Currently, we only support a batch size of 1 for each GPU. We will modify it later to allow batch processing.

**Comment by LZ-CH** [comment] 2024-12-11 15:33
Hi, After I have finished training with lora, how can I evaluation it? Can you give me a more detailed command example? Because I have tried to execute the command under eval by myself, I encountered the problem of ```trying to set a tensor of shape torch.size([152064, 3584]) in "weight" (which has shape torch.size([32000, 3584])), this looks incorrect.``` when loading the model, so I want to ask for a more clear execution method.

**Comment by zd11024** [comment] 2024-12-12 16:14
I haved fixed the bugs in the latest commit. Please refer to `scripts/3d/train/train_multi_lora.sh` and `scripts/3d/eval/eval_scan2cap_lora.sh` for training and inference, respectively.

**Comment by LZ-CH** [comment] 2024-12-13 04:01
Thank you very much! After reading the modified code, I would like to ask, when fine-tuning in lora, does --mm_tunable_parts need to be set to None? Because I saw that you set ```--mm_tunable_parts="mm_vision_tower,mm_mlp_adapter,mm_language_model"``` in ```train_multi_lora.sh```, which seems to affect the model saving strategy in ```llava_trainer.py```, so I want to confirm it.

**Comment by zd11024** [comment] 2024-12-13 04:30
In the latest commit, if you set `lora_enable` to `true`, the parameter `mm_tunable_parts` will be ignored. And we only make the parameters of `*_lora`, `embeds_token`, `world_postion_embedding`, and `ground_head` trainable. https://github.com/LaVi-Lab/Video-3D-LLM/blob/463ef00acde78e9d6b82eeeecccaa90377428b47/llava/train/train_3d.py#L1759

**Comment by LZ-CH** [comment] 2024-12-16 10:28
Hi, when I use the new code to fine-tune the model with lora (with 16 uniform frames), I can get relatively normal results in tasks such as ScanQA、SQA3D and  Scan2cap, but the results are extremely poor in grounding tasks such as scanrefer. I would like to know why this is the case? The following are the results on scanrefer:

```shell
all iou@0.25: 5.395456457719814
all iou@0.5: 5.185107278081615
multiple iou@0.25: 5.245987211274958
multiple iou@0.5: 4.984992822654313
unique iou@0.25: 6.016260162601626
unique iou@0.5: 6.016260162601626
```
The following are the results on SQA3D:
```shell
all: 55.78289286729184
what: 47.86399302528335
which: 49.572649572649574
can: 67.75147928994083
is: 69.1717791411043
how: 54.19354838709678
others: 54.416961130742045
```
The following are the results on ScanQA:
```shell
ratio: 0.8845815945529447
count: 4675
CIDER: 98.83342700546838
BLEU: 45.316620611896155, 30.94921801753157, 23.040511857596222, 16.463154472532068
METEOR: 19.12336883119447
Rouge: 47.489073524726344
EM: 0.29775401069518714
```

The following are the results on Scan2cap:
```shell
ratio: 0.788602265984777
CIDER: 60.69167272961569
BLEU: 36.5773621449065
METEOR: 26.91046202716036
Rouge: 61.04655948592808
```

**Comment by zd11024** [comment] 2024-12-16 10:51
Sorry, I didn’t express myself clearly before. We only tried LoRA on QA tasks, and the performance was similar to that without LoRA, which is consistent with your results.
For captioning and visual grounding, the results may look reasonable. Because the output of LLM is under the text space, and visual grounding requires regressing region features, using only LoRA may not be able to learn the alignment.
A possible solution is to unfreeze the last few layers of LLM during training.

**Comment by zd11024** [comment] 2024-12-24 05:07
I am closing this issue now. Please feel free to reopen it if needed.

**Closed by zd11024** 2024-12-24 05:07 UTC

**Comment by FightSH** [comment] 2025-11-27 07:53
> Hi, when I use the new code to fine-tune the model with lora (with 16 uniform frames), I can get relatively normal results in tasks such as ScanQA、SQA3D and Scan2cap, but the results are extremely poor in grounding tasks such as scanrefer. I would like to know why this is the case? The following are the results on scanrefer:
> 
> all iou@0.25: 5.395456457719814
> all iou@0.5: 5.185107278081615
> multiple iou@0.25: 5.245987211274958
> multiple iou@0.5: 4.984992822654313
> unique iou@0.25: 6.016260162601626
> unique iou@0.5: 6.016260162601626
> The following are the results on SQA3D:
> 
> all: 55.78289286729184
> what: 47.86399302528335
> which: 49.572649572649574
> can: 67.75147928994083
> is: 69.1717791411043
> how: 54.19354838709678
> others: 54.416961130742045
> The following are the results on ScanQA:
> 
> ratio: 0.8845815945529447
> count: 4675
> CIDER: 98.83342700546838
> BLEU: 45.316620611896155, 30.94921801753157, 23.040511857596222, 16.463154472532068
> METEOR: 19.12336883119447
> Rouge: 47.489073524726344
> EM: 0.29775401069518714
> The following are the results on Scan2cap:
> 
> ratio: 0.788602265984777
> CIDER: 60.69167272961569
> BLEU: 36.5773621449065
> METEOR: 26.91046202716036
> Rouge: 61.04655948592808



> Hi, when I use the new code to fine-tune the model with lora (with 16 uniform frames), I can get relatively normal results in tasks such as ScanQA、SQA3D and Scan2cap, but the results are extremely poor in grounding tasks such as scanrefer. I would like to know why this is the case? The following are the results on scanrefer:
> 
> all iou@0.25: 5.395456457719814
> all iou@0.5: 5.185107278081615
> multiple iou@0.25: 5.245987211274958
> multiple iou@0.5: 4.984992822654313
> unique iou@0.25: 6.016260162601626
> unique iou@0.5: 6.016260162601626
> The following are the results on SQA3D:
> 
> all: 55.78289286729184
> what: 47.86399302528335
> which: 49.572649572649574
> can: 67.75147928994083
> is: 69.1717791411043
> how: 54.19354838709678
> others: 54.416961130742045
> The following are the results on ScanQA:
> 
> ratio: 0.8845815945529447
> count: 4675
> CIDER: 98.83342700546838
> BLEU: 45.316620611896155, 30.94921801753157, 23.040511857596222, 16.463154472532068
> METEOR: 19.12336883119447
> Rouge: 47.489073524726344
> EM: 0.29775401069518714
> The following are the results on Scan2cap:
> 
> ratio: 0.788602265984777
> CIDER: 60.69167272961569
> BLEU: 36.5773621449065
> METEOR: 26.91046202716036
> Rouge: 61.04655948592808

Hello, I'm also conducting LoRA experiments using two 48GB GPUs, and my training takes about 6 days per epoch. Could you please share your LoRA training configuration and training time per epoch?
